### ISSUE TITLE
Python issues

### ISSUE THREAD

**Issue by TrashBirdEcology** [natbprice/tvdiff#1]
- [ ] Add Python and python libraries are installed to the README

- [ ] Test example.RMD on a fresh install of Python on WINDOWS os

- [ ] Add  test for Python path, 

- [ ] User must use R__32-bit__ on Windows OS. Add a warning or error if using 64-bit. Include link for instructions (or just describe) how to switch from 64 to 32-bit. Will require R restart if switching.

- [ ] Test example.RMD on MacOSx

**Comment by natbprice** [comment]
Python code has been removed. Method is implemented entirely in base R.
